
export const Loadouts = {
  OpsCoreNightfall: {
    name: 'OpsCore Nightfall',
    primary: '#1A1A1A',
    accent: '#D32F2F',
    text: '#F5F5F5',
    highlight: '#FFC107',
    background: '#121212',
    muted: '#AAAAAA',
    card: '#1F1F1F',
    subtle: '#F0F0F0',
  },
  GhostDivision: {
    name: 'Ghost Division',
    primary: '#2C2C2E',
    accent: '#00BCD4',
    text: '#E0F7FA',
    highlight: '#B2EBF2',
    background: '#0D0D0D',
    muted: '#AAAAAA',
    card: '#1F1F1F',
    subtle: '#F0F0F0',
  },
  AegisProtocol: {
    name: 'Aegis Protocol',
    primary: '#263238',
    accent: '#8BC34A',
    text: '#FFFFFF',
    highlight: '#FF9800',
    background: '#111111',
    muted: '#AAAAAA',
    card: '#1F1F1F',
    subtle: '#F0F0F0',
  },
  Hellion: {
    name: 'Hellion',
    primary: '#212121',
    accent: '#FF3D00',
    text: '#FFEBEE',
    highlight: '#FF6D00',
    background: '#121212',
    muted: '#AAAAAA',
    card: '#1F1F1F',
    subtle: '#F0F0F0',
  },
  CommandCenter: {
    name: 'Command Center',
    primary: '#37474F',
    accent: '#009688',
    text: '#ECEFF1',
    highlight: '#00E5FF',
    background: '#102027',
    muted: '#AAAAAA',
    card: '#1F1F1F',
    subtle: '#F0F0F0',
  },
  ArclightClearance: {
    name: 'Arclight Clearance',
    primary: '#1B1B1B',
    accent: '#FFD600',
    text: '#FAFAFA',
    highlight: '#F44336',
    background: '#000000',
    muted: '#AAAAAA',
    card: '#1F1F1F',
    subtle: '#F0F0F0',
  },
};
